import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs/promises';

const FALLBACK_TEMPLATE = `
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DocMaster AI - Executive Report</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-50 p-8 font-sans antialiased text-gray-900">
    <div class="max-w-4xl mx-auto bg-white shadow-xl rounded-2xl overflow-hidden border border-gray-100">
        <!-- Header -->
        <div class="bg-gradient-to-r from-blue-600 to-indigo-700 px-8 py-6 text-white">
            <h1 class="text-3xl font-bold">Executive Insight Report</h1>
            <p class="mt-2 text-blue-100 opacity-90 text-sm">Generated by DocMaster AI</p>
        </div>

        <div class="p-8 space-y-8 lg:p-10">
            <!-- Summary Section -->
            <section class="bg-blue-50/50 rounded-xl p-6 border border-blue-100">
                <h2 class="text-xl font-semibold text-blue-900 mb-4 flex items-center gap-2">
                    <svg class="w-6 h-6 text-blue-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    핵심 요약 (Executive Summary)
                </h2>
                <div class="text-gray-700 leading-relaxed text-lg prose prose-blue">{{summary}}</div>
            </section>

            <!-- Chart & Data Insight Section -->
            <section class="bg-white rounded-xl p-6 border border-gray-200 shadow-sm">
                <h2 class="text-xl font-semibold text-gray-800 mb-4 border-b pb-2">도식 및 데이터 분석 (Data Insights)</h2>
                <div class="text-gray-600 prose prose-lg prose-indigo">{{chart_description}}</div>
            </section>

            <!-- Action Items Section -->
            <section class="bg-rose-50/40 rounded-xl p-6 border border-rose-100">
                <h2 class="text-xl font-semibold text-rose-900 mb-4 flex items-center gap-2">
                    <svg class="w-6 h-6 text-rose-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    결정 및 액션 아이템 (Action Items & Risk)
                </h2>
                <div class="text-gray-800 prose prose-lg prose-rose">{{action_item}}</div>
            </section>
        </div>
        
        <!-- Footer -->
        <div class="bg-gray-50 border-t border-gray-100 px-8 py-4 text-center text-sm text-gray-500">
            Confidential - Internal Use Only
        </div>
    </div>
</body>
</html>
`;

export class TemplateManager {
    public async getTemplate(): Promise<string> {
        // Check workspace local template
        if (!vscode.workspace.workspaceFolders || vscode.workspace.workspaceFolders.length === 0) {
            return FALLBACK_TEMPLATE;
        }

        const workspaceRoot = vscode.workspace.workspaceFolders[0].uri.fsPath;
        const templatePath = path.join(workspaceRoot, '.docmaster', 'template.html');

        try {
            await fs.access(templatePath);
            const content = await fs.readFile(templatePath, 'utf-8');
            vscode.window.showInformationMessage('Local custom template (.docmaster/template.html) used.');
            return content;
        } catch {
            // File does not exist, use fallback
            return FALLBACK_TEMPLATE;
        }
    }
}
